version: "3"
services:

  odoo:
    image: odoo:15.0
    build: ./build
    ports:
      - 8069:8069
    container_name: odoo15
    environment:
      - DB_ENV_POSTGRES_USER=odoo
      - DB_ENV_POSTGRES_PASSWORD=odoo
    links:
      - db:db
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./filestore:/var/lib/odoo
    network_mode: "bridge"

  db:
    image: postgres:10.0
    container_name: odoo15_db
    hostname: odoo15_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./data:/var/lib/postgresql/data
    network_mode: "bridge"
